name: cypress

on:
  pull_request:
      branches: '**'
  push:
      branches: '**'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: bahmutov/npm-install@v1

    - run: yarn build
    - run: yarn build:es
    - run: yarn build:all

    - name: Cypress dependencies
      uses: cypress-io/github-action@v2
      with:
        install: true
        runTests: false

    - uses: cypress-io/github-action@v2
      with:
        group: frontend-example-project-test
        working-directory: examples/frontend-webpack-project
        install: false
        record: true
        start: yarn serve -l 8080 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: query-parameter-overrides-test
        working-directory: tests/webpack-projects/query-parameter-overrides
        install: false
        record: true
        start: yarn serve -l 8990 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: cypress-plugin-test
        working-directory: tests/webpack-projects/cypress-plugin
        install: false
        record: true
        start: yarn serve -l 8991 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: app-config-core-in-browser-test
        working-directory: tests/webpack-projects/app-config-core-in-browser
        install: false
        record: true
        start: yarn serve -l 8992 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: app-config-two-app-config-sources
        working-directory: tests/webpack-projects/two-app-config-sources
        install: false
        record: true
        start: yarn serve -l 8993 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: app-config-extending-other-files
        working-directory: tests/webpack-projects/extending-other-files
        install: false
        record: true
        start: yarn serve -l 8994 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: app-config-webpack5
        working-directory: tests/webpack-projects/webpack5
        install: false
        record: true
        start: yarn serve -l 8995 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - uses: cypress-io/github-action@v2
      with:
        group: app-config-vite
        working-directory: examples/vite-project
        install: false
        record: true
        start: yarn serve -l 8996 ./dist
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
