name: docker-image

on:
  push:
      branches: 'master'
      tags: '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: |
            ghcr.io/launchcodedev/app-config:latest

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - uses: docker/build-push-action@v2
        if: contains(github.ref, 'refs/tags/')
        with:
          push: true
          tags: |
            ghcr.io/launchcodedev/app-config:${{ steps.tagName.outputs.tag }}
