name: macos

on:
  push:
    branches: 'master'

jobs:
  # for master, we test Linux & Windows & MacOS + Node LTS & Latest
  # note that we don't do linting here, only on Linux + Node LTS
  all:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [14.x, 16.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1

    - run: yarn playwright install-deps chromium
    - run: yarn build
    - run: yarn build:es
    - run: yarn build:all
    - run: yarn test --testTimeout 20000
      env: { CI: 1 }

